---
name: concourse
director_uuid: d420097e-4217-495c-945b-6c55ec47b0d7
releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: large 
  stemcell: trusty
  azs: [AZ_01]
  networks: [{name: Deployment}]
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
     # external_url: http://172.28.81.103

      # replace with username/password, or configure GitHub auth
      basic_auth_username: concourse
      basic_auth_password: welcome1

      postgresql_database: &atc_db atc
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: large
  stemcell: trusty
  # replace with a disk type from your BOSH Director's cloud config
  persistent_disk_type: '5120'
  azs: [AZ_01]
  networks: [{name: Deployment}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: admin 
        password: admin 

- name: worker
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: xlarge
  stemcell: trusty
  azs: [AZ_01]
  networks: [{name: Deployment}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

